"""Module 5 -- automated clinical reporting and archiving.

Assembles one standardised report from the encounter: context, triage, POCUS findings,
quantitative measures, reasoning, decision support, and the safety envelope. Renders it
deterministically, and archives it with a content hash so that what was shown to a clinician
can be recovered later and proven unaltered.

Two decisions in here are safety decisions rather than presentation ones.

**NOT ASSESSED is a section, not an omission.** A modality that was never examined gets its
own heading in the report, next to what was found and what was screened for and not found.
Omitting it would leave a reader to infer absence from silence, and silence is what a normal
result looks like. The three-state distinction the schema preserves is worth nothing if the
report collapses it at the last step.

**A withheld differential is rendered as withheld.** The report does not quietly drop the
reasoning section when validation failed; it prints the refusal and the reason. A report that
simply lacks a differential is indistinguishable from one where the model was never asked.
"""
from __future__ import annotations

import hashlib
import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPORT_VERSION = "1.0"

DISCLAIMER = (
    "Generated by an AI decision-support prototype. Not a diagnostic device. Not validated "
    "against clinical outcomes. Every finding, alert and recommendation requires clinician "
    "verification, and the clinical decision remains the clinician's.")


def build_report(state: dict, result: dict, support: dict) -> dict[str, Any]:
    """The structured report. `result` is reason()'s output; `support` is decision_support()'s.

    Pure assembly: every value here already exists upstream and nothing is recomputed, so the
    report cannot disagree with the system that produced it.
    """
    imaging = state["imaging"]
    detected = [f for f in imaging["findings"] if f["detected"]]
    screened = [f for f in imaging["findings"] if not f["detected"]]
    diff = result.get("differential") or {}
    withheld = bool(result.get("differential_withheld"))

    # Quantitative measures reported by the modules, e.g. an ejection fraction.
    measures: list[dict[str, Any]] = []
    for organ, rep in (state.get("_reports") or {}).items():
        for name, value in (rep.get("measurements") or {}).items():
            measures.append({"organ": organ, "measure": name, "value": value})

    report: dict[str, Any] = {
        "report_version": REPORT_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "encounter_id": state.get("encounter_id"),

        "context": {
            **(state.get("demographics") or {}),
            "scenario": support["scenario"]["label"],
            "scenario_matched_on": support["scenario"].get("matched_on"),
        },

        "triage": {
            "urgency": (state.get("triage") or {}).get("urgency"),
            "confidence": (state.get("triage") or {}).get("confidence"),
            # Present only when a model proposed a tier for this encounter. The archived record
            # is where this belongs: it is not something a clinician needs while assessing the
            # patient, and it is exactly what someone reviewing the encounter afterwards --
            # or auditing how the two assessments compare over many encounters -- would need.
            "agreement": state.get("triage_agreement"),
        },

        "pocus": {
            "detected": [{"organ": f["organ"], "finding": f["label"],
                          "confidence": f["confidence"], "evidence": f["evidence"]}
                         for f in detected],
            "screened_not_detected": [{"organ": f["organ"], "finding": f["label"],
                                       "confidence": f["confidence"]} for f in screened],
            # Its own key, deliberately. See the module docstring.
            "not_assessed": sorted(set(list(imaging.get("organs_not_assessed") or [])
                                       + list(support["scenario"].get("not_assessed") or []))),
            "model_limitations": list(imaging.get("out_of_scope") or []),
        },

        "quantitative_measures": measures,

        "values": {
            "vitals": state.get("vitals") or {},
            "labs": state.get("labs") or {},
            "never_measured": {"labs": state["missing"]["labs"],
                               "vitals": state["missing"]["vitals"]},
        },

        "reasoning": {
            "withheld": withheld,
            "withheld_reason": result.get("validation_errors") if withheld else None,
            "differential": diff.get("differential") or [],
            "uncertainty": diff.get("uncertainty"),
            "missing_information": diff.get("missing_information") or [],
            "warnings": result.get("warnings") or [],
            "evidence_considered": result.get("evidence_considered") or [],
            "retrieval": result.get("retrieval"),
        },

        "decision_support": {
            "severity": support["severity"],
            "alerts": support["alerts"],
            "additional_examinations": support["additional_examinations"],
            "therapeutic": support["therapeutic"],
        },

        "safety": {
            "escalation": result.get("escalation"),
            "case_quality": state.get("case_quality"),
            "conflicts": state.get("conflicts") or [],
            "thresholds_version": support.get("thresholds_version"),
            "disclaimer": DISCLAIMER,
        },
    }

    report["conclusion"] = standardised_conclusion(report)
    return report


def standardised_conclusion(report: dict) -> str:
    """One paragraph, assembled from the report by fixed rules.

    Written by template rather than by the model on purpose. The conclusion is the line a busy
    reader will act on, and it must say the same thing as the rest of the report; generating it
    would introduce a place where it could differ.
    """
    sev = report["decision_support"]["severity"]
    esc = report["safety"]["escalation"] or {}
    p = report["pocus"]
    parts: list[str] = []

    parts.append(f"{report['context'].get('scenario', 'Unclassified')} presentation assessed "
                 f"at {sev['severity']} severity.")

    if p["detected"]:
        found = ", ".join(f"{d['finding']} ({d['organ']}, {d['confidence']:.2f})"
                          for d in p["detected"])
        parts.append(f"Point-of-care ultrasound detected {found}.")
    elif p["screened_not_detected"]:
        parts.append(f"Point-of-care ultrasound screened "
                     f"{len(p['screened_not_detected'])} finding(s) and detected none; this "
                     f"does not exclude pathology the models do not represent.")
    else:
        parts.append("No point-of-care ultrasound finding is recorded.")

    if p["not_assessed"]:
        parts.append(f"NOT ASSESSED: {', '.join(p['not_assessed'])} — expected for this "
                     f"presentation and never examined.")

    crit = [a for a in report["decision_support"]["alerts"] if a["severity"] == "CRITICAL"]
    if crit:
        parts.append(f"{len(crit)} critical alert(s): "
                     f"{'; '.join(a['message'] for a in crit)}.")

    if report["reasoning"]["withheld"]:
        parts.append("The differential was WITHHELD because the generated reasoning did not "
                     "pass validation against the record.")
    elif report["reasoning"]["differential"]:
        top = report["reasoning"]["differential"][0]
        parts.append(f"Leading consideration: {top.get('diagnosis')} "
                     f"({top.get('likelihood')} likelihood).")

    if esc.get("escalate"):
        parts.append(f"ESCALATED — {len(esc.get('triggers') or [])} trigger(s); route "
                     f"{esc.get('route')}.")
    else:
        parts.append("No escalation trigger; the case may be answered directly.")

    high = [r for r in report["decision_support"]["additional_examinations"]
            if r["priority"] == "HIGH"]
    if high:
        parts.append(f"Most informative next: {', '.join(r['exam'] for r in high[:3])}.")

    return " ".join(parts)


# ---------------------------------------------------------------------------------------
def render_report(report: dict) -> str:
    """The report as text, deterministic for a given report object."""
    L: list[str] = []
    a = L.append

    a("=" * 78)
    a(f"CLINICAL REPORT  {report['encounter_id']}")
    a(f"generated {report['generated_at']}   report v{report['report_version']}")
    a("=" * 78)

    a("\nCONCLUSION")
    a("  " + report["conclusion"])

    sev = report["decision_support"]["severity"]
    a(f"\nSEVERITY: {sev['severity']}   (triage {sev['triage_urgency']}, "
      f"escalation {'YES' if sev['escalation'] else 'no'})")
    for r in sev["reasons"]:
        a(f"  - {r}")

    alerts = report["decision_support"]["alerts"]
    ncrit = sum(1 for al in alerts if al["severity"] == "CRITICAL")
    # Counted by severity rather than headed "critical alerts" over a list that also contains
    # warnings, which overstates the first line a reader looks at.
    a(f"\nALERTS: {ncrit} critical, {len(alerts) - ncrit} warning")
    if not alerts:
        a("  none")
    for al in alerts:
        a(f"  [{al['severity']}] {al['type']}: {al['message']}")

    c = report["context"]
    a("\nCONTEXT")
    for k in sorted(c):
        a(f"  {k}: {c[k]}")
    t = report["triage"]
    a(f"  triage: {t['urgency']} (confidence {t['confidence']})"
      if t["urgency"] else "  triage: not available")

    p = report["pocus"]
    a("\nPOCUS FINDINGS")
    if p["detected"]:
        for d in p["detected"]:
            a(f"  DETECTED      {d['organ']}: {d['finding']} "
              f"({d['confidence']:.2f}, evidence {d['evidence']})")
    else:
        a("  DETECTED      none")
    for d in p["screened_not_detected"]:
        a(f"  NOT DETECTED  {d['organ']}: {d['finding']} ({d['confidence']:.2f}) "
          f"-- screened for and not seen")
    if p["not_assessed"]:
        a("  NOT ASSESSED  " + ", ".join(p["not_assessed"]))
        a("                a gap in the record, NOT a negative result")
    for lim in p["model_limitations"]:
        a(f"  LIMIT         {lim}")

    if report["quantitative_measures"]:
        a("\nQUANTITATIVE MEASURES")
        for m in report["quantitative_measures"]:
            a(f"  {m['organ']}: {m['measure']} = {m['value']}")

    v = report["values"]
    a("\nVITALS AND LABORATORY")
    for group in ("vitals", "labs"):
        for k in sorted(v[group]):
            e = v[group][k]
            flag = "" if e.get("flag") == "normal" else f"   <-- {str(e.get('flag')).upper()}"
            ref = f" (ref {e['reference']})" if e.get("reference") else ""
            a(f"  {k}: {e.get('value')} {e.get('unit', '')}{ref}{flag}")
    nm = v["never_measured"]["labs"] + v["never_measured"]["vitals"]
    if nm:
        a("  NEVER MEASURED: " + ", ".join(nm))
        a("                  absent, NOT normal")

    r = report["reasoning"]
    a("\nCLINICAL REASONING")
    if r["withheld"]:
        a("  DIFFERENTIAL WITHHELD -- the generated reasoning did not pass validation")
        for e in (r["withheld_reason"] or []):
            a(f"    - {e}")
        a("  The reasoning below is shown for inspection and is NOT offered as an answer.")
    for i, d in enumerate(r["differential"], 1):
        a(f"  {i}. {d.get('diagnosis')} ({d.get('likelihood')})")
        for s in (d.get("supporting") or []):
            a(f"       supports:  {s}")
        for s in (d.get("contradicting") or []):
            a(f"       against:   {s}")
        for s in (d.get("limitations") or []):
            a(f"       limit:     {s}")
    if r["uncertainty"]:
        a(f"  uncertainty: {r['uncertainty']}")
    if r["evidence_considered"]:
        a("  evidence considered (built from the state, not from the answer):")
        for e in r["evidence_considered"]:
            a(f"    {'*' if e['used'] else ' '} {e['id']} {e['text']}")
    for w in r["warnings"]:
        a(f"  warning: {w}")

    ds = report["decision_support"]
    a("\nRECOMMENDED ADDITIONAL EXAMINATIONS")
    if not ds["additional_examinations"]:
        a("  none -- the record is complete for this presentation")
    for rec in ds["additional_examinations"]:
        a(f"  [{rec['priority']}] {rec['exam']}")
        a(f"          {rec['reason']}")
    a("  The system recommends examinations; it does not order them.")

    th = ds["therapeutic"]
    a("\nTHERAPEUTIC CONSIDERATIONS")
    if not th["considerations"]:
        a(f"  none -- {th['status']}")
        if th.get("note"):
            a(f"  {th['note']}")
    for c_ in th["considerations"]:
        a(f"  CONSIDER: {c_['consideration']}")
        a(f"    basis: {c_['basis']} [{c_['passage']}]")
        a(f"    {c_['disclaimer']}")

    s = report["safety"]
    esc = s["escalation"] or {}
    a("\nSAFETY")
    a(f"  escalation: {'YES' if esc.get('escalate') else 'no'}  route {esc.get('route')}")
    for t_ in (esc.get("triggers") or []):
        a(f"    - {t_}")
    if s["conflicts"]:
        for c_ in s["conflicts"]:
            a(f"  conflict: {c_}")
    q = s["case_quality"] or {}
    a(f"  case quality: {q.get('grade')}")
    a(f"  alert thresholds: config v{s.get('thresholds_version')}")

    a("\n" + "-" * 78)
    a(DISCLAIMER)
    a("=" * 78)
    return "\n".join(L)


# ---------------------------------------------------------------------------------------
def archive_report(report: dict, root: str | Path, *, text: str | None = None) -> dict[str, str]:
    """Write the report to the archive, atomically, with a content hash.

    The hash is over the canonical JSON with the generation timestamp removed, so the same
    encounter reprocessed by the same system produces the same digest and a genuine change is
    distinguishable from a re-run. Writes go through a temporary file and a replace, because a
    half-written report that still parses would be worse than none.
    """
    root = Path(root)
    (root / "reports").mkdir(parents=True, exist_ok=True)

    stable = {k: v for k, v in report.items() if k != "generated_at"}
    digest = hashlib.sha256(
        json.dumps(stable, sort_keys=True, default=str).encode("utf8")).hexdigest()
    report = {**report, "content_sha256": digest}

    eid = report.get("encounter_id") or "unknown"
    paths = {}
    for suffix, payload in (("json", json.dumps(report, indent=2, default=str)),
                            ("txt", text if text is not None else render_report(report))):
        dest = root / "reports" / f"{eid}.{suffix}"
        fd, tmp = tempfile.mkstemp(dir=dest.parent, suffix=f".{suffix}.tmp")
        with os.fdopen(fd, "w", encoding="utf8") as fh:
            fh.write(payload)
        os.replace(tmp, dest)
        paths[suffix] = str(dest)

    return {**paths, "sha256": digest}
